name: fruit-classifier-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - streamlit
    - tensorflow==2.15.0
    - numpy
    - pillow
    - scipy
    - scikit-learn
    - matplotlib
    - h5py